<a href="https://colab.research.google.com/github/bashamahabshaik/ml-dl-python-practice/blob/main/tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
#Reshape and view
my_torch1 = my_torch.reshape(2,5)
my_torch1

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [16]:
#Reshape if we dont know the no.of items using -1
my_torch2 = torch.arange(15)
my_torch2 = my_torch2.reshape(3,-1)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [18]:
my_torch3 = torch.arange(10)
my_torch3 = my_torch3.view(2,5)
my_torch3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
#Difference b/w shape and view


Imagine you have a box of Lego blocks arranged in a 3x4 grid.

reshape: You can rearrange the Lego blocks into a different shape, like a 2x6 grid or a 1x12 line. Reshape is like taking apart the Lego grid and building a new shape. It creates a new arrangement but doesn’t care how the blocks are originally stored inside. If needed, it can create a new set of blocks entirely (copy the data).

view: View is like looking at the same Lego blocks from a different angle or dividing them into groups without actually moving them. The blocks are still in the same original order, but you’re just organizing them differently in your head. However, you can only "view" if the Lego blocks are already neatly stored (contiguous in memory).

1. reshape:

Purpose: Changes the shape of a tensor, but it can return a new tensor if the original data isn’t stored contiguously in memory.
Behavior: It’s more flexible because it can internally copy the data if needed to create a tensor with the desired shape.
Use Case: When you want to change the shape of a tensor without worrying about how the data is stored in memory.
2. view:

Purpose: Also changes the shape of a tensor, but it works only if the tensor is contiguous in memory (i.e., data is stored in a single, continuous block).
Behavior: It doesn’t create a new tensor or copy the data. Instead, it provides a new view of the same underlying data with a different shape.
Use Case: When you want a lightweight operation to change the shape without duplicating memory, and you know the tensor is contiguous.

In [29]:


# Step 1: Create a simple tensor
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("Original Tensor:")
print(tensor)

# Check if the tensor is contiguous
print("\nIs the original tensor contiguous?", tensor.is_contiguous())

# Step 2: Use reshape
reshaped = tensor.reshape(3, 2)
print("\nReshaped Tensor (3x2):")
print(reshaped)

# Step 3: Use view (works because the tensor is contiguous)
viewed = tensor.view(3, 2)
print("\nViewed Tensor (3x2):")
print(viewed)

# Step 4: Make the tensor non-contiguous by transposing it
non_contiguous = tensor.t()  # Transpose flips rows and columns
print("\nNon-Contiguous Tensor (Transpose):")
print(non_contiguous)

# Check if the tensor is contiguous
print("\nIs the transposed tensor contiguous?", non_contiguous.is_contiguous())

# Step 5: Try to use view on the non-contiguous tensor
try:
    viewed_non_contiguous = non_contiguous.view(3, 2)
    print("\nViewed Non-Contiguous Tensor (result might be wrong!):")
    print(viewed_non_contiguous)
except RuntimeError as e:
    print("\nError when using view on non-contiguous tensor:", e)

# Step 6: Use reshape on the non-contiguous tensor (this will work)
reshaped_non_contiguous = non_contiguous.reshape(3, 2)
print("\nReshaped Non-Contiguous Tensor:")
print(reshaped_non_contiguous)


Original Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])

Is the original tensor contiguous? True

Reshaped Tensor (3x2):
tensor([[1, 2],
        [3, 4],
        [5, 6]])

Viewed Tensor (3x2):
tensor([[1, 2],
        [3, 4],
        [5, 6]])

Non-Contiguous Tensor (Transpose):
tensor([[1, 4],
        [2, 5],
        [3, 6]])

Is the transposed tensor contiguous? False

Viewed Non-Contiguous Tensor (result might be wrong!):
tensor([[1, 4],
        [2, 5],
        [3, 6]])

Reshaped Non-Contiguous Tensor:
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [30]:
#Reshape and view will update
my_torch5 = torch.arange(10)
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [31]:
my_torch5[1]=4141
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [32]:
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [34]:
my_torch7 = torch.arange(10)
my_torch8 = my_torch7.view(2,5)
my_torch8

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [37]:
my_torch7[1]=4242
my_torch7

tensor([   0, 4242,    2,    3,    4,    5,    6,    7,    8,    9])

In [38]:
my_torch8

tensor([[   0, 4242,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [42]:
#SLICING
my_torch9 = torch.arange(10)
my_torch9[7]

tensor(7)

In [46]:
my_torch10 = my_torch9.reshape(5,2)
my_torch10

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [47]:
my_torch10[:,1]

tensor([1, 3, 5, 7, 9])

In [48]:
my_torch10[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])