<a href="https://colab.research.google.com/github/bashamahabshaik/ml-dl-python-practice/blob/main/tensor_maths.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
t1 = torch.tensor([1,2,3,4])
t2 = torch.tensor([5,6,7,8])

In [3]:
t1,t2

(tensor([1, 2, 3, 4]), tensor([5, 6, 7, 8]))

In [5]:
#ADD
t1+t2

tensor([ 6,  8, 10, 12])

In [6]:
torch.add(t1,t2)

tensor([ 6,  8, 10, 12])

In [7]:
#SUBTRACT
t2-t1

tensor([4, 4, 4, 4])

In [8]:
torch.sub(t2,t1)

tensor([4, 4, 4, 4])

In [9]:
#MULTIPLY
t1*t2

tensor([ 5, 12, 21, 32])

In [10]:
torch.mul(t1,t2)

tensor([ 5, 12, 21, 32])

In [12]:
#DIVIDE
t2/t1

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [13]:
torch.div(t2,t1)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [14]:
#REMAINDER
t2%t1

tensor([0, 0, 1, 0])

In [15]:
torch.remainder(t2,t1)

tensor([0, 0, 1, 0])

In [16]:
torch.pow(t1,t2)

tensor([    1,    64,  2187, 65536])

In [20]:
t1.add(t2)#Other way to t1+t2, torch.add(t1,t2)

tensor([ 6,  8, 10, 12])