<a href="https://colab.research.google.com/github/bashamahabshaik/ml-dl-python-practice/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Tensors**

Tensor is a multi dimensional matrix containing elements of a single datatype.

In [2]:
import torch
import numpy as np

In [3]:
list1  = [[1,2,3,4,5],[6,7,8,9,10]]
list1

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [5]:
np1 = np.random.rand(3,4)
np1

array([[0.47891416, 0.76179158, 0.58876835, 0.89637832],
       [0.95508642, 0.00362749, 0.82694828, 0.86810409],
       [0.2706466 , 0.67479912, 0.59525588, 0.81264651]])

In [6]:
np1.dtype

dtype('float64')

In [11]:
tensor_2d = torch.randn(3,4)
tensor_2d
# tensor_2d.dtype

tensor([[-0.7660,  0.5185,  0.8679, -2.2047],
        [-0.4338,  0.5195, -1.3909, -2.0401],
        [-0.5199,  0.8557,  0.4914,  1.4800]])

In [12]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.4789, 0.7618, 0.5888, 0.8964],
        [0.9551, 0.0036, 0.8269, 0.8681],
        [0.2706, 0.6748, 0.5953, 0.8126]], dtype=torch.float64)